In [ ]:
import pandas as pd

df = pd.read_json('/content/drive/MyDrive/Colab Notebooks/datasets/News_Category_Dataset_v3.json', lines=True)
df.head()



link  \
0  https://www.huffpost.com/entry/covid-boosters-...   
1  https://www.huffpost.com/entry/american-airlin...   
2  https://www.huffpost.com/entry/funniest-tweets...   
3  https://www.huffpost.com/entry/funniest-parent...   
4  https://www.huffpost.com/entry/amy-cooper-lose...   

                                            headline   category  \
0  Over 4 Million Americans Roll Up Sleeves For O...  U.S. NEWS   
1  American Airlines Flyer Charged, Banned For Li...  U.S. NEWS   
2  23 Of The Funniest Tweets About Cats And Dogs ...     COMEDY   
3  The Funniest Tweets From Parents This Week (Se...  PARENTING   
4  Woman Who Called Cops On Black Bird-Watcher Lo...  U.S. NEWS   

                                   short_description               authors  \
0  Health experts said it is too early to predict...  Carla K. Johnson, AP   
1  He was subdued by passengers and crew when he ...        Mary Papenfuss   
2  "Until you have a dog you don't understand wha...         Elyse Wanshel   
3  "Accidentally put grown-up toothpaste on my to...      Caroline Bologna   
4  Amy Cooper accused investment firm Franklin Te...        Nina Golgowski   

        date  
0 2022-09-23  
1 2022-09-23  
2 2022-09-23  
3 2022-09-23  
4 2022-09-22

In [ ]:
# Define the topics to exclude
excluded_topics = ['POLITICS', 'WELLNESS','ENTERTAINMENT']

# Drop entries based on the condition excluding the specified topics
filtered_df = df[df['category'].isin(excluded_topics)]


In [ ]:
filtered_df = df

In [ ]:
len(filtered_df['category'].unique())

42

In [ ]:
# X = df['headline']+ " "+ df['short_description']
X = filtered_df['short_description']

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tfidf = TfidfVectorizer(max_df=0.95, min_df=2, stop_words='english')

In [ ]:
dtm = tfidf.fit_transform(X)

In [ ]:
dtm

<209527x43523 sparse matrix of type '<class 'numpy.float64'>'
	with 1981547 stored elements in Compressed Sparse Row format>

In [ ]:
from sklearn.decomposition import NMF

In [ ]:
nmf_model = NMF(n_components=3,random_state=42)

In [ ]:
# nmf_model.fit(dtm)
# from sklearn.decomposition import NMF
# from sklearn.metrics import precision_score, recall_score, average_precision_score
# from sklearn.model_selection import train_test_split


# X_eval = tfidf.transform(X_eval)
# X_eval_pred = nmf_model.transform(X_eval)
# precision = precision_score(X_eval, X_eval_pred, average='micro')
# recall = recall_score(X_eval, X_eval_pred, average='micro')
# average_precision = average_precision_score(X_eval, X_eval_pred)

# print("Precision:", precision)
# print("Recall:", recall)
# print("Average Precision:", average_precision)

In [ ]:
len(tfidf.get_feature_names_out())

43523

In [ ]:
import random

In [ ]:
len(nmf_model.components_)

3

In [ ]:
nmf_model.components_

array([[3.83113814e-03, 1.12337035e-01, 1.05018099e-03, ...,
        4.95485226e-05, 3.59043353e-04, 2.01543934e-04],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [8.52761415e-06, 2.45456261e-02, 0.00000000e+00, ...,
        4.01027580e-05, 0.00000000e+00, 0.00000000e+00]])

In [ ]:
len(nmf_model.components_[0])

43523

In [ ]:
single_topic = nmf_model.components_[0]

In [ ]:
top_word_indices = single_topic.argsort()[-10:]

In [ ]:
for index in top_word_indices:
    print(tfidf.get_feature_names_out()[index])

year
life
day
new
know
don
people
like
time
just


In [ ]:
for index,topic in enumerate(nmf_model.components_):
    print(f'THE TOP 15 WORDS FOR TOPIC #{index}')
    print([tfidf.get_feature_names_out()[i] for i in topic.argsort()[-15:]])
    print('\n')

THE TOP 15 WORDS FOR TOPIC #0
['good', 'love', 'think', 've', 'make', 'year', 'life', 'day', 'new', 'know', 'don', 'people', 'like', 'time', 'just']


THE TOP 15 WORDS FOR TOPIC #1
['home', 'weddings', 'stylelist', 'touch', 'huffpoststyle', 'instagram', 'style', 'sure', 'tumblr', 'want', 'pinterest', 'huffpost', 'facebook', 'twitter', 'check']


THE TOP 15 WORDS FOR TOPIC #2
['state', 'hillary', 'presidential', 'says', 'administration', 'obama', 'white', 'clinton', 'republican', 'house', 'campaign', 'said', 'donald', 'president', 'trump']




In [ ]:
dtm

<209527x43523 sparse matrix of type '<class 'numpy.float64'>'
	with 1981547 stored elements in Compressed Sparse Row format>

In [ ]:
dtm.shape

(209527, 43523)

In [ ]:
topic_results = nmf_model.transform(dtm)

In [ ]:
topic_results.shape

(209527, 3)

In [ ]:
topic_results[0]

array([0.00925654, 0.        , 0.01254263])

In [ ]:
for i in range(10):
  print(i)
  print(topic_results[0].round(i))

0
[0. 0. 0.]
1
[0. 0. 0.]
2
[0.01 0.   0.01]
3
[0.009 0.    0.013]
4
[0.0093 0.     0.0125]
5
[0.00926 0.      0.01254]
6
[0.009257 0.       0.012543]
7
[0.0092565 0.        0.0125426]
8
[0.00925654 0.         0.01254263]
9
[0.00925654 0.         0.01254263]


In [ ]:
topic_results[0].argmax()

2

In [ ]:
filtered_df['Topic'] = topic_results.argmax(axis=1)

In [ ]:
filtered_df.head()


link  \
0  https://www.huffpost.com/entry/covid-boosters-...   
1  https://www.huffpost.com/entry/american-airlin...   
2  https://www.huffpost.com/entry/funniest-tweets...   
3  https://www.huffpost.com/entry/funniest-parent...   
4  https://www.huffpost.com/entry/amy-cooper-lose...   

                                            headline   category  \
0  Over 4 Million Americans Roll Up Sleeves For O...  U.S. NEWS   
1  American Airlines Flyer Charged, Banned For Li...  U.S. NEWS   
2  23 Of The Funniest Tweets About Cats And Dogs ...     COMEDY   
3  The Funniest Tweets From Parents This Week (Se...  PARENTING   
4  Woman Who Called Cops On Black Bird-Watcher Lo...  U.S. NEWS   

                                   short_description               authors  \
0  Health experts said it is too early to predict...  Carla K. Johnson, AP   
1  He was subdued by passengers and crew when he ...        Mary Papenfuss   
2  "Until you have a dog you don't understand wha...         Elyse Wanshel   
3  "Accidentally put grown-up toothpaste on my to...      Caroline Bologna   
4  Amy Cooper accused investment firm Franklin Te...        Nina Golgowski   

        date  Topic  
0 2022-09-23      2  
1 2022-09-23      2  
2 2022-09-23      0  
3 2022-09-23      0  
4 2022-09-22      0

In [ ]:
df_new = df. copy()

In [ ]:
#### topic identiication using lda

In [ ]:
df

link  \
0       https://www.huffpost.com/entry/covid-boosters-...   
1       https://www.huffpost.com/entry/american-airlin...   
2       https://www.huffpost.com/entry/funniest-tweets...   
3       https://www.huffpost.com/entry/funniest-parent...   
4       https://www.huffpost.com/entry/amy-cooper-lose...   
...                                                   ...   
209522  https://www.huffingtonpost.com/entry/rim-ceo-t...   
209523  https://www.huffingtonpost.com/entry/maria-sha...   
209524  https://www.huffingtonpost.com/entry/super-bow...   
209525  https://www.huffingtonpost.com/entry/aldon-smi...   
209526  https://www.huffingtonpost.com/entry/dwight-ho...   

                                                 headline   category  \
0       Over 4 Million Americans Roll Up Sleeves For O...  U.S. NEWS   
1       American Airlines Flyer Charged, Banned For Li...  U.S. NEWS   
2       23 Of The Funniest Tweets About Cats And Dogs ...     COMEDY   
3       The Funniest Tweets From Parents This Week (Se...  PARENTING   
4       Woman Who Called Cops On Black Bird-Watcher Lo...  U.S. NEWS   
...                                                   ...        ...   
209522  RIM CEO Thorsten Heins' 'Significant' Plans Fo...       TECH   
209523  Maria Sharapova Stunned By Victoria Azarenka I...     SPORTS   
209524  Giants Over Patriots, Jets Over Colts Among  M...     SPORTS   
209525  Aldon Smith Arrested: 49ers Linebacker Busted ...     SPORTS   
209526  Dwight Howard Rips Teammates After Magic Loss ...     SPORTS   

                                        short_description  \
0       Health experts said it is too early to predict...   
1       He was subdued by passengers and crew when he ...   
2       "Until you have a dog you don't understand wha...   
3       "Accidentally put grown-up toothpaste on my to...   
4       Amy Cooper accused investment firm Franklin Te...   
...                                                   ...   
209522  Verizon Wireless and AT&T are already promotin...   
209523  Afterward, Azarenka, more effusive with the pr...   
209524  Leading up to Super Bowl XLVI, the most talked...   
209525  CORRECTION: An earlier version of this story i...   
209526  The five-time all-star center tore into his te...   

                     authors       date  Topic  
0       Carla K. Johnson, AP 2022-09-23      2  
1             Mary Papenfuss 2022-09-23      2  
2              Elyse Wanshel 2022-09-23      0  
3           Caroline Bologna 2022-09-23      0  
4             Nina Golgowski 2022-09-22      0  
...                      ...        ...    ...  
209522      Reuters, Reuters 2012-01-28      0  
209523                       2012-01-28      0  
209524                       2012-01-28      0  
209525                       2012-01-28      0  
209526                       2012-01-28      0  

[209527 rows x 7 columns]

In [ ]:
!pip install nltk
!pip install gensim


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from gensim import corpora

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

def preprocess_documents(documents):
    lemmatizer = WordNetLemmatizer()
    stop_words = set(stopwords.words('english'))

    tokenized_docs = [word_tokenize(doc.lower()) for doc in documents]
    cleaned_docs = [[lemmatizer.lemmatize(token) for token in doc if token.isalpha() and token not in stop_words] for doc in tokenized_docs]
    dictionary = corpora.Dictionary(cleaned_docs)
    document_term_matrix = [dictionary.doc2bow(doc) for doc in cleaned_docs]

    return dictionary, document_term_matrix

from gensim.models import LdaModel

def train_lda_model(document_term_matrix, num_topics):
    lda_model = LdaModel(document_term_matrix, num_topics=num_topics, id2word=dictionary, passes=10)
    return lda_model

def extract_topics(lda_model):
    topics = lda_model.print_topics()
    return topics


# Step 2: Preprocess the data
documents = filtered_df['short_description']
dictionary, document_term_matrix = preprocess_documents(documents)



[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...


In [ ]:
filtered_df['short_description']

0         Health experts said it is too early to predict...
1         He was subdued by passengers and crew when he ...
2         "Until you have a dog you don't understand wha...
3         "Accidentally put grown-up toothpaste on my to...
4         Amy Cooper accused investment firm Franklin Te...
                                ...                        
209522    Verizon Wireless and AT&T are already promotin...
209523    Afterward, Azarenka, more effusive with the pr...
209524    Leading up to Super Bowl XLVI, the most talked...
209525    CORRECTION: An earlier version of this story i...
209526    The five-time all-star center tore into his te...
Name: short_description, Length: 209527, dtype: object

In [ ]:
# Step 3: Train the LDA model
num_topics = len(filtered_df['category'].unique())
lda_model = train_lda_model(document_term_matrix, num_topics)

# Step 4: Extract topics
topics = extract_topics(lda_model)

# Print the topics
for topic in topics:
    print(topic)

(21, '0.085*"found" + 0.047*"man" + 0.037*"president" + 0.034*"able" + 0.034*"spend" + 0.033*"death" + 0.032*"obama" + 0.029*"celebrate" + 0.028*"alone" + 0.024*"former"')
(37, '0.097*"always" + 0.070*"thought" + 0.064*"girl" + 0.052*"set" + 0.035*"result" + 0.034*"anyone" + 0.031*"including" + 0.031*"gift" + 0.024*"team" + 0.023*"usually"')
(20, '0.099*"help" + 0.065*"whether" + 0.058*"summer" + 0.040*"everything" + 0.038*"talk" + 0.036*"house" + 0.035*"choice" + 0.034*"small" + 0.032*"white" + 0.031*"research"')
(29, '0.211*"new" + 0.055*"study" + 0.050*"mean" + 0.049*"ever" + 0.046*"video" + 0.044*"york" + 0.039*"start" + 0.029*"holiday" + 0.021*"time" + 0.018*"magazine"')
(36, '0.095*"going" + 0.078*"give" + 0.049*"must" + 0.046*"celebrity" + 0.030*"using" + 0.030*"system" + 0.030*"form" + 0.026*"key" + 0.025*"looked" + 0.024*"wall"')
(13, '0.068*"live" + 0.055*"idea" + 0.051*"fact" + 0.051*"others" + 0.030*"attention" + 0.029*"popular" + 0.028*"local" + 0.026*"service" + 0.025*"di

In [ ]:
lda_model.save('lda_model.model')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
#trying to figure out the topic based upon the available result

In [ ]:
# Example news description
new_description = ["Health experts said it is too early to predict whether demand would match up with the 171 million doses of the new boosters the U.S. ordered for the fall."]

# Preprocess the new news description
dictionary, document_term_matrix = preprocess_documents(new_description)

# Convert the preprocessed description to a bag of words representation
# new_article_bow = dictionary.doc2bow(preprocessed_description)

# Infer the topic distribution for the new news description
topic_distribution = lda_model.get_document_topics(document_term_matrix)

# Sort the topics by their probability scores
sorted_topics = sorted(topic_distribution, key=lambda x: x[1], reverse=True)

# Get the most probable topic
most_probable_topic = sorted_topics[0]
print(most_probable_topic)
topic_id = most_probable_topic[0][0]

# Get the topic name based on the topic ID
print(topic_id)
topic_name = topics[topic_id]

# Print the most probable topic
print("Most Probable Topic:", topic_name)

[(3, 0.081946485), (9, 0.07313111), (15, 0.12253845), (20, 0.09250755), (25, 0.237122), (29, 0.075724766), (30, 0.1704889), (33, 0.08870973)]
3
Most Probable Topic: (29, '0.211*"new" + 0.055*"study" + 0.050*"mean" + 0.049*"ever" + 0.046*"video" + 0.044*"york" + 0.039*"start" + 0.029*"holiday" + 0.021*"time" + 0.018*"magazine"')


In [ ]:
len(most_probable_topic)

8

In [ ]:
df = pd.read_json('/content/drive/MyDrive/Colab Notebooks/datasets/News_Category_Dataset_v3.json', lines=True)

new_df = df.drop(columns=['authors','link','date'])
new_df.head()

headline   category  \
0  Over 4 Million Americans Roll Up Sleeves For O...  U.S. NEWS   
1  American Airlines Flyer Charged, Banned For Li...  U.S. NEWS   
2  23 Of The Funniest Tweets About Cats And Dogs ...     COMEDY   
3  The Funniest Tweets From Parents This Week (Se...  PARENTING   
4  Woman Who Called Cops On Black Bird-Watcher Lo...  U.S. NEWS   

                                   short_description  
0  Health experts said it is too early to predict...  
1  He was subdued by passengers and crew when he ...  
2  "Until you have a dog you don't understand wha...  
3  "Accidentally put grown-up toothpaste on my to...  
4  Amy Cooper accused investment firm Franklin Te...

In [ ]:
from wordcloud import WordCloud, STOPWORDS
import matplotlib.pyplot as plt

In [ ]:


# create final dataframe of combined headline and short_description
final_df = new_df.copy()
final_df['length_of_news'] = final_df['headline'] + final_df['short_description']
final_df.drop(['headline','short_description'], inplace=True, axis=1)
final_df['len_news'] = final_df['length_of_news'].map(lambda x: len(x))

In [ ]:
# Top categories by and number of articles per categories
cat_df = pd.DataFrame(new_df['category'].value_counts()).reset_index()
cat_df.rename(columns={'index':'news_classes','category':'numcat'}, inplace=True)

In [ ]:
# create new dataframe of category and length of each news articles in that categories
ndf = final_df.copy()
ndf.drop('len_news', inplace=True, axis=1)

# list of top 10  categories in out dataset
categories = cat_df['news_classes'][:10].to_list()

# list of news articles of each top 10 categories list
articles_list = []

for i in categories:
    cat_ndf = ndf[ndf['category'] == i]
    cat_array = cat_ndf['length_of_news'].values  # array of news articles text in each category
    articles_list.append(cat_array)
    
# create a wordcloud instance
wc1 = WordCloud(max_words=1000, 
               min_font_size=10,
               height=600,
               width=1600,
               background_color='black',
               contour_color='black',
               colormap='plasma',
               repeat=True,
               stopwords=STOPWORDS)

# plot the figure of 10 wordcloud from out dataset
plt.figure(figsize=(15,15))

for idx, j in enumerate(categories):
    plt.subplot(5,2,idx+1)
    cloud = wc1.generate(' '.join(articles_list[idx]))
    plt.imshow(cloud, interpolation= "bilinear")
    plt.title(f"Wordcloud for news topic {j}")
    plt.axis('off')